// Runs the real inline script with DOM/event stubs; no browser/package dependency.
const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const html = fs.readFileSync(process.argv[2] || 'templates/index.html', 'utf8');
const script = html.match(/<script[^>]*>([\s\S]*?)<\/script>/)[1];
const nativeMax = Number(html.match(/<textarea[^>]*maxlength="(\d+)"/)?.[1] || Infinity);
const events = () => ({listeners: {}, addEventListener(name, fn) {this.listeners[name] = fn;}});
const message = {...events(), value: '', error: '', setCustomValidity(text) {this.error = text;}};
const send = {disabled: false};
const window = events();
let submissions = 0;
const form = {...events(), requestSubmit() {
    if (message.error || !message.value || message.value.length > nativeMax) return;
    const event = {preventDefault() {this.prevented = true;}};
    this.listeners.submit(event);
    if (!event.prevented) submissions++;
}};
vm.runInNewContext(script, {document: {getElementById: id => ({'chat-form': form, message, send})[id]}, window});
const reset = () => {window.listeners.pageshow(); submissions = 0;};
const input = value => {message.value = value; message.listeners.input?.();};
const enter = extra => message.listeners.keydown({key: 'Enter', shiftKey: false, isComposing: false, keyCode: 13,
                                                preventDefault() {}, ...extra});
input('🚀'.repeat(4000)); enter();
assert.equal(submissions, 1, 'Exactly 4000 Unicode code points must be sendable');
reset(); input('x'.repeat(4001)); enter();
assert.equal(submissions, 0, 'Over 4000 code points must be rejected');
reset(); input('Halo'); enter({shiftKey: true});
assert.equal(submissions, 0, 'Shift+Enter must not submit');
enter({isComposing: true}); enter({keyCode: 229});
assert.equal(submissions, 0, 'IME composition must not submit');
enter(); enter();
assert.equal(submissions, 1, 'Enter sends once, including repeated keydown');
assert.equal(send.disabled, true);
reset(); assert.equal(send.disabled, false); assert.equal(message.readOnly, false);
input('e\u0301'.repeat(2000)); enter(); assert.equal(submissions, 1);
reset(); input('\u0085' + 'x'.repeat(4000) + '\u001c'); enter();
assert.equal(submissions, 1, 'Whitespace removed by Python must not consume the message limit');
reset(); input('\ufeff' + 'x'.repeat(4000)); enter();
assert.equal(submissions, 0, 'BOM is not stripped by Python and must count toward the limit');
console.log('10 frontend checks passed (Unicode and whitespace boundaries, Enter, Shift+Enter, IME, duplicate submit, back navigation).');
